{
 "title": "EOSBP",
 "tags": [ "eos" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "3s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "content": "<h1><b>EOS Store BP</h1>" },
  {
   "title": "节点监控",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "eos_bp_node_info",
     "query": "SELECT * FROM \"eoserror\" WHERE (\"region\" = 'ap') AND $timeFilter GROUP BY \"host\" LIMIT 5",
     "region": "default",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ],
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "eos-full-node",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 2 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "eos_full_node_info",
     "select": [
      [
       { "params": [ "*" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "内存剩余",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Memory" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU 剩余率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "CPU" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": { "filter": "CPU idle time" },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "网卡em3流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 17 },
   "yaxes": [
    { "format": "bps", "label": "速率" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Network interfaces" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": {
      "filter": "Incoming network traffic on ens3"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/  剩余率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "/data  剩余率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-mbp" ],
       "text": "setAlias(eos-mbp)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-mbp" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-sbp1" ],
       "text": "setAlias(eos-sbp1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-sbp1" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-1" ],
       "text": "setAlias(eos-hid-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-1" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-1-2" ],
       "text": "setAlias(eos-hid-fn-1-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-1-2" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-1" ],
       "text": "setAlias(eos-hid-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-1" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-hid-fn-2-2" ],
       "text": "setAlias(eos-hid-fn-2-2)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-hid-fn-2-2" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-1-1" ],
       "text": "setAlias(eos-open-fn-1-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-1-1" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Filesystems" },
     "functions": [
      {
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "eos-open-fn-2-1" ],
       "text": "setAlias(eos-open-fn-2-1)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "eos-open-fn-2-1" },
     "item": {
      "filter": "Free disk space on /data (percentage)"
     },
     "options": {
      "showDisabledItems": true
     },
     "table": {
      "skipEmptyValues": false
     },
     "textFilter": "eth0",
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}